### ISSUE TITLE
Actividad 8

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-awua-de-limon#1]
[Practica 8.pdf](https://github.com/user-attachments/files/17547981/Practica.8.pdf)

**Comment by saul19bautista** [comment]
buen trabajo realizado, entendible y bien estructurado 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
