### ISSUE TITLE
Practica 10

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-awua-de-limon#2]
[Practica.10.pdf](https://github.com/user-attachments/files/18056554/Practica.10.pdf)

**Comment by Arlet04** [comment]
Cumple con portada y los escudos institucionales: 25 puntos
Describe el procedimiento: 25 puntos
Describe las illustraciones detalladamente: 25 puntos
Muestra resultados y conclusiones: 25 puntos
Puntaje alcanzado 100% = 50 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
